source 'https://gitee.com/AnthonyCoder/SLBaiSiSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'SLToolObjCKit_Example' do
  pod 'SLToolObjCKit', :path => '../'

  target 'SLToolObjCKit_Tests' do
    inherit! :search_paths

    
  end
end
